plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

jar {
    archiveBaseName = "cacio-java-compat"
    destinationDirectory.set(file("../app_onyxlauncher/src/main/assets/components/caciocavallo17/"))
}
